// Action Type Constant
export const LOAD_PLAYERS_SUCCESS = 'LOAD_PLAYERS_SUCCESS'; // called after API call succeeds
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const SEARCH_BY_POSITION = 'SEARCH_BY_POSITION';
export const SEARCH_BY_NATIONALITY = 'SEARCH_BY_NATIONALITY';
export const SEARCH_BY_JERSEY_NUMBER = 'SEARCH_BY_JERSEY_NUMBER';
export const SEARCH_BY_CONTRACT_UNTIL = 'SEARCH_BY_CONTRACT_UNTIL';
export const SEARCH_BY_BIRTHDAY = 'SEARCH_BY_BIRTHDAY';
